export * from './day1.js';
export * from './day11.js';
export * from './day2.js';
export * from './day3.js';
export * from './day6.js';
export * from './day7.js';
export * from './day8.js';
export * from './day9.js';
export * from './day12.js';
